### ISSUE TITLE
Rake setup:cluster failed - delivery-cli RPM package not signed

### ISSUE THREAD

**Issue by shanesveller** [chef-cookbooks/delivery-cluster#173] opened 2015-11-19 17:48 UTC
Using commit 2c37c08ea5e45279d4114aee69fa7653f97842d6, and ChefDK 0.10.0 on OSX 10.11.1.

Ran `rake setup:generate_env` and opted for a Vagrant-based cluster initially. Using the suggested default of [opscode-centos-6.6](https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box) for the VMs.

When running `rake setup:delivery_build_nodes`, it ultimately fails on `chef_ingredient[delivery-cli] action upgrade` with the following underlying reason:

```
[...]
yum -d0 -e0 -y --disablerepo=* --enablerepo=chef-stable  install delivery-cli-20150811030818+20150811030818-1.el6 returned 1:
                                 STDOUT:
                                 STDERR:

                                 Package delivery-cli-20150811030818+20150811030818-1.el6.x86_64.rpm is not signed
```

I've also submitted an issue on chef-ingredient repo regarding the test-kitchen suites, because I wanted to add a kitchen suite to demonstrate this problem more easily:

https://github.com/chef-cookbooks/chef-ingredient/issues/63

**Comment by shanesveller** [comment] 2015-11-19 18:46
Switching to the bento ubuntu-14.04 vagrant box, I get the following during the build-node provisioning:
```
apt_package[push-client] (/var/chef/cache/cookbooks/chef-ingredient/libraries/debian_handler.rb line 66) had an error: Chef::Exceptions::Package: opscode-push-jobs-client has no candidate in the apt-cache
```

**Comment by stephenlauck** [comment] 2015-11-20 17:29
There is an update in the delivery_build cookbook that allows a '--nogpgcheck' for installing the delivery-cli. The real fix would be to generate a new build of delivery-cli RPM and sign it.

**Comment by afiune** [comment] 2015-11-23 13:31
@shanesveller: As Stephen was saying, what you need to do as a workaround is to modify your environment file you generated with `rake setup:generate_env` which is located at `delivery-cluster/environments`. Add the following options parameter to the **builders** block:
```
 "builders": {
    <- extra options depending on your driver ->
    "delivery-cli": {
       "options": "--nogpgcheck"
    }
  }
```

**Comment by afiune** [comment] 2015-11-23 14:01
@shanesveller I have verified the second problem you listed here and I can confirm that it is a current problem we have with `chef-ingredient` and the rename of our product `push-jobs` to `push-client`. 
```
============================================================================
Error executing action `install` on resource 'chef_ingredient[push-client]'
============================================================================

Chef::Exceptions::Package
-------------------------
apt_package[push-client] (/var/chef/cache/cookbooks/chef-ingredient/libraries/debian_handler.rb line 66) had an error: Chef::Exceptions::Package: opscode-push-jobs-client has no candidate in the apt-cache
```

There is already some issues/PRs opened here to track down the work done:
https://github.com/chef-cookbooks/chef-ingredient/issues/59
https://github.com/chef-cookbooks/chef-ingredient/pull/66

I am going to close this issue since the first problem you described has a current workaround. Please open another issue for the second one. Thank you for you feedback! :+1:

**Closed by afiune** 2015-11-23 14:01 UTC
Labels: question

**Comment by shanesveller** [comment] 2015-11-23 15:11
@afiune Thanks for the response!

**Comment by afiune** [comment] 2015-11-23 16:09
@shanesveller You are very welcome.. Thank you for the feedback. :smile:
