### ISSUE TITLE
rake destroy:builders does not terminate AWS EC2 instances

### ISSUE THREAD

**Issue by psprings** [chef-cookbooks/delivery-cluster#171] opened 2015-11-06 03:10 UTC
# Summary
When the disk space on build-nodes reach 100%, the easiest standardized practice right now is to run `rake destroy:builders` then `rake setup:delivery_build_nodes`

If a project needs the build-nodes, the build will fail because "no build nodes available"
Checking the AWS console will reveal that there are duplicates of all build nodes because the original build nodes never got destroyed. Terminating all original EC2 build-node instances will fix the issue.

# Details
**Driver:** AWS
* `rake destroy:builders`
  * *EXPECT:* Nodes removed from Chef server
    * *RESULT:* Nodes removed from Chef server
  * *EXPECT:* Build-nodes terminated in AWS
    * *RESULT:* No instances terminated
* Execute a build (phase run)
  * *EXPECT:* "Could not start phase run. No build nodes available"
    * *RESULT:* "Could not start phase run. No build nodes available"
* `rake setup:delivery_build_nodes`
  * *EXPECT:* New build nodes to spin up in AWS
    * *RESULT:* New build nodes created in AWS
* Execute a build (phase run)
  * *EXPECT:* Start the build
    * *RESULT:* "no build nodes available"

**Comment by afiune** [comment] 2015-11-06 14:05
@psprings I have seen that problem with the `destroy` action. We are going to fix this as soon as possible. 

But that problem where you `setup` new build-nodes and you don't have then available, that sound like something I haven't seen. Would you mind validating this and help us understand more of this second issue that you are describing?

Thank you for reporting this!! :smile:

**Comment by afiune** [comment] 2015-11-10 21:18
Duplicate of https://github.com/chef-cookbooks/delivery-cluster/issues/163

**Comment by stephenlauck** [comment] 2015-11-19 15:02
Fix is here https://github.com/chef/chef-provisioning-aws/pull/403

**Closed** 2015-12-08 15:29 UTC
Labels: bug, duplicate, InProgress
