### ISSUE TITLE
Error: File name too long

### ISSUE THREAD

**Issue by tpetchel** [chef-cookbooks/delivery-cluster#161] opened 2015-09-28 20:46 UTC
When I run `rake setup:cluster` I get this in the output. The cookbook continues to run, so not sure what the net effect is. Looks like some recursion hell?

Output follows - notice the long line starting with "/opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1402"

```
Vendoring delivery-cluster (0.3.17) to cookbooks/delivery-cluster
/opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1402:in `initialize': File name too long @ rb_sysopen - /var/folders/8t/yfsrbt5n4170hdcjvdq8nhrc0000gp/T/vendor20150928-29206-1ufo5no/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/chef-splunk/test/fixtures/cookbooks/test/files/default/sanitycheck/appserver/modules/PrerequisiteChecker/PrerequisiteChecker.conf (Errno::ENAMETOOLONG)
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1402:in `open'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1402:in `block in copy_file'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1401:in `open'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1401:in `copy_file'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1369:in `copy'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:469:in `block in copy_entry'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1506:in `call'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1506:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1509:in `block in wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1508:in `wrap_traverse'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:466:in `copy_entry'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:441:in `block in cp_r'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1588:in `block in fu_each_src_dest0'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1586:in `each'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1586:in `fu_each_src_dest0'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:440:in `cp_r'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:606:in `block (2 levels) in vendor'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:588:in `each'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:588:in `block in vendor'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:581:in `vendor'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:387:in `vendor'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:52:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:27:in `execute!'
	from /opt/chefdk/embedded/apps/berkshelf/bin/berks:5:in `<top (required)>'
	from /opt/chefdk/bin/berks:44:in `load'
	from /opt/chefdk/bin/berks:44:in `<main>'

Current chef environment => environments/test.json
```

**Comment by afiune** [comment] 2015-09-28 21:53
Woow! I haven't seen that! it is just looping to itself when trying to vendor the cookbooks. I would like to know what version of `chefdk` are you using? and anything else helped me understand this behavior.

**Comment by tpetchel** [comment] 2015-09-29 17:36
```
$ chef --version
Chef Development Kit Version: 0.7.0
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.2
```

I don't have any other info for you. I was using the SSH provisioner, nothing else special. Will report back if it persists.

**Comment by tpetchel** [comment] 2015-09-29 17:37
BTW, just tried with the AWS driver - I do see the same error.

**Comment by afiune** [comment] 2015-10-09 23:08
@tpetchel I can't reproduce this so I might need more info .. I am not sure what though.

**Comment by afiune** [comment] 2015-11-12 15:22
I am closing this Issue since I think it was something particular to the environment and I haven't been able to replicate it. If you see it again please reopen it and we will try to reproduce it again. Thank you!

**Closed by afiune** 2015-11-12 15:22 UTC
Labels: help wanted
